name: StoryDriven Media Group
favicon: null
layout_spectrum: 0.6213569925166667
typography_spectrum: 0.34465
title: strydrvn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58585a'
    - '#a4c8d4'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.75
  lightness: 0.6463015680201352
  saturation: 0.36359744635410607
  rhythmicContrast: 0.25
purpose: []
