name: StoryDriven Media Group
favicon: null
layout_spectrum: 0.6213569925166667
typography_spectrum: 0.6058624195866287
title: strydrvn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.16524241189472377
  lightness: 0.6463015680201352
  saturation: 0.36359744635410607
  rhythmicContrast: 0.2570546302013099
purpose: []
